---
record_0:
  Title: 'Wild Center evalutation '
  Start time: 11/29/2013 9:30
  Stop time: 11/29/2013 9:40
  Room: 'D1F Conference Room '
  Abstract: 
  Column span: '3'
  Off set: 
  Created at: 
  Updated at: 
  Row span: 
  Background color: "#2489ce"
  Speakers: Yuan Sheng
  Speaker introduction: 
  Activity type: keynote
